EXPERIMENT:
  NAME: ""
  TAG: "vanilla1,res32x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "NONE"
  STUDENT: "resnet32x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 60
  LR: 0.05
  LR_DECAY_STAGES: [10, 30, 60]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
  TRAINER: "base"
LOG:
  SAVE_CHECKPOINT_FREQ: 5
